<% env = JSON.parse(File.read('/home/ujjawal/environment.json')) %>

development:
  username: root
  password: foobar
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  database: wtfornot_dev
  timeout: 5000

test:
  username: root
  password: foobar
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wtfornot_test
  timeout: 5000

production:
  username: <% env['DOTCLOUD_DATA_MYSQL_LOGIN'] %>
  password: KdWzGqztcKVhn7Mzfvca
  adapter: mysql2
  encoding: utf8
  host: <% env['DOTCLOUD_DATA_MYSQL_HOST'] %>
  port: <% env['DOTCLOUD_DATA_MYSQL_PORT'] %>
  pool: 5
  reconnect: false
  database: wtfornot_production
  timeout: 5000
