<% env = JSON.parse(File.read('/home/dotcloud/environment.json')) %>

development:
  username: root
  password: foobar
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  database: wtfornot_dev
  timeout: 5000

test:
  username: root
  password: foobar
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wtfornot_test
  timeout: 5000

production:
  #username: <% env['DOTCLOUD_DATA_MYSQL_LOGIN'] %>
  username: root
  password: KdWzGqztcKVhn7Mzfvca
  adapter: mysql2
  encoding: utf8
  #host: <% env['DOTCLOUD_DATA_MYSQL_HOST'] %>
  host: newgiaf-uast23.dotcloud.com
  #port: <% env['DOTCLOUD_DATA_MYSQL_PORT'] %>
  port: 14583
  pool: 5
  reconnect: false
  database: wtfornot_production
  timeout: 5000
